# -*- coding: utf-8 -*-
"""treinamento_powerbi_26042025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qOKOlC20R5oVEK-scVtDXKgEVJGQUko
"""

import streamlit as st

st.title("Treinamento Interativo de Power BI")
st.write("Marque cada item concluído, avalie a dificuldade e deixe observações!")

# Função para avaliação de dificuldade
def avaliacao_dificuldade(passo):
    st.subheader(f"Avaliação do {passo}")
    dificuldade = st.radio("Como você classificaria a dificuldade?", ["Fácil", "Médio", "Difícil"], key=f"{passo}_dificuldade")
    observacoes = st.text_area("Observações ou dificuldades encontradas:", key=f"{passo}_obs")
    return dificuldade, observacoes

# Primeiro Passo
st.header("Primeiro Passo: Compreender os Dados")
with st.form("passo1"):
    st.subheader("Importando Base de Dados")
    check1 = st.checkbox("Importar bases de clientes")
    check2 = st.checkbox("Transformar dados (Power Query)")
    check3 = st.checkbox("Renomear 'Planilha 1' para 'CadastroClientes'")
    check4 = st.checkbox("Visão geral do Power Query")

    st.subheader("Tratando a Primeira Base de Dados")
    check5 = st.checkbox("Apagar coluna 9 e 10 e testar Ctrl+Z")
    check6 = st.checkbox("Remover linhas em branco")
    check7 = st.checkbox("Usar a primeira linha como cabeçalho")
    check8 = st.checkbox("Observar se o Power BI tipou corretamente")
    check9 = st.checkbox("Transformar coluna de CPF em texto")
    check10 = st.checkbox("Excluir coluna número de filhos")
    check11 = st.checkbox("Entender que o Power BI não altera o Excel")

    st.subheader("Tratando a Base Cadastro Clientes")
    check12 = st.checkbox("Substituir valores de gênero (M/F)")
    check13 = st.checkbox("Ajustar data no formato americano")
    check14 = st.checkbox("Mesclar coluna nome + sobrenome")
    check15 = st.checkbox("Comparar aba Transformar vs Adicionar Coluna")
    check16 = st.checkbox("Navegar pelas etapas aplicadas")
    check17 = st.checkbox("Modificar maiúsculas e minúsculas")

    st.subheader("Tratando a Base Cadastro Produtos")
    check18 = st.checkbox("Adicionar base CadastroProdutos")
    check19 = st.checkbox("Verificar ponto decimal na origem")
    check20 = st.checkbox("Dividir preço e custo unitário por 100")
    check21 = st.checkbox("Dividir coluna Produto por delimitador")
    check22 = st.checkbox("Renomear novas colunas")

    st.subheader("Ferramentas de Texto e Otimização")
    check23 = st.checkbox("Adicionar base CadastroLojas")
    check24 = st.checkbox("Modificar RG Gerente para texto")
    check25 = st.checkbox("Extrair nome da rua do endereço")
    check26 = st.checkbox("Modificar nome da coluna na fórmula")
    check27 = st.checkbox("Inserir últimos 9 caracteres do CEP")
    check28 = st.checkbox("Modificar parâmetros com engrenagem")

    st.subheader("Coluna de Exemplos")
    check29 = st.checkbox("Criar coluna de Bairro com exemplos")

    st.subheader("Importar da Pasta")
    check30 = st.checkbox("Obter dados de pasta")
    check31 = st.checkbox("Filtrar por 'Base Vendas'")
    check32 = st.checkbox("Excluir coluna com nome de arquivos")

    st.subheader("Ferramentas de Data - Tabela Calendário")
    check33 = st.checkbox("Criar tabela calendário dinâmica")
    check34 = st.checkbox("Adicionar colunas de Mês, Ano, Semana, etc.")

    submitted1 = st.form_submit_button("Salvar progresso do Primeiro Passo")
    if submitted1:
        st.success("Progresso do Primeiro Passo salvo!")

dificuldade1, observacoes1 = avaliacao_dificuldade("Primeiro Passo")

# Segundo Passo
st.header("Segundo Passo: Relacionar Mais de Uma Tabela")
with st.form("passo2"):
    st.subheader("Relacionamentos no Power BI")
    check35 = st.checkbox("Entender tabelas fato e dimensão")
    check36 = st.checkbox("Identificar tabelas fato e características")
    check37 = st.checkbox("Organizar características em cima, fatos embaixo")

    st.subheader("Criando Relacionamentos")
    check38 = st.checkbox("Relacionar Base Vendas + Cadastro Produtos")
    check39 = st.checkbox("Relacionar Base Vendas + Cadastro Clientes")
    check40 = st.checkbox("Relacionar Base Vendas + Calendário")
    check41 = st.checkbox("Relacionar Base Vendas + Cadastro Lojas")

    submitted2 = st.form_submit_button("Salvar progresso do Segundo Passo")
    if submitted2:
        st.success("Progresso do Segundo Passo salvo!")

dificuldade2, observacoes2 = avaliacao_dificuldade("Segundo Passo")

# Terceiro Passo
st.header("Terceiro Passo: Realizar os Cálculos Adequados")
with st.form("passo3"):
    st.subheader("Fórmulas DAX")
    check42 = st.checkbox("Introdução às fórmulas DAX")

    st.subheader("Colunas Calculadas")
    check43 = st.checkbox("Criar coluna Tipo de Pedido")

    st.subheader("Medidas")
    check44 = st.checkbox("Criar medida Total de Pedidos")

    st.subheader("Colunas x Medidas")
    check45 = st.checkbox("Entender contexto de linha e filtro")

    st.subheader("DAX - Principais Fórmulas")
    check46 = st.checkbox("Criar fórmulas de Ano, Mês, Dia da Semana")
    check47 = st.checkbox("Calcular Idade do Cliente")
    check48 = st.checkbox("Criar IF de Categoria")
    check49 = st.checkbox("Concatenar nome completo")
    check50 = st.checkbox("Aplicar LEFT e UPPER para mês abreviado")
    check51 = st.checkbox("Usar função RELATED")
    check52 = st.checkbox("Criar medidas de vendas e faturamento")
    check53 = st.checkbox("Aplicar funções AVERAGE, MAX, MIN, COUNT")
    check54 = st.checkbox("Aplicar CALCULATE para vendas de celular")

    submitted3 = st.form_submit_button("Salvar progresso do Terceiro Passo")
    if submitted3:
        st.success("Progresso do Terceiro Passo salvo!")

dificuldade3, observacoes3 = avaliacao_dificuldade("Terceiro Passo")

# Quarto Passo
st.header("Quarto Passo: Apresentar os Dados")
with st.form("passo4"):
    st.subheader("Tipos de Gráficos")
    check55 = st.checkbox("Gráfico de Área")
    check56 = st.checkbox("Gráfico de Colunas")
    check57 = st.checkbox("Gráfico de Colunas Empilhadas")
    check58 = st.checkbox("Gráfico de Barras")
    check59 = st.checkbox("Gráfico de Mapa")
    check60 = st.checkbox("Cartões")

    submitted4 = st.form_submit_button("Salvar progresso do Quarto Passo")
    if submitted4:
        st.success("Progresso do Quarto Passo salvo!")

dificuldade4, observacoes4 = avaliacao_dificuldade("Quarto Passo")

# Resultado Final
st.header("Resumo do Seu Progresso")
if st.button("Enviar progresso final"):
    st.success("Progresso enviado com sucesso! Obrigado por participar!")
    st.write("**Avaliação de Dificuldade:**")
    st.write(f"Primeiro Passo: {dificuldade1}")
    st.write(f"Segundo Passo: {dificuldade2}")
    st.write(f"Terceiro Passo: {dificuldade3}")
    st.write(f"Quarto Passo: {dificuldade4}")
    st.write("**Observações:**")
    st.write(f"Primeiro Passo: {observacoes1}")
    st.write(f"Segundo Passo: {observacoes2}")
    st.write(f"Terceiro Passo: {observacoes3}")
    st.write(f"Quarto Passo: {observacoes4}")
    st.info("Elas por Elas Bemol. ❤️")

