# -*- coding: utf-8 -*-
"""Untitled49.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qOKOlC20R5oVEK-scVtDXKgEVJGQUko
"""

# !pip install streamlit

import streamlit as st

st.title("Treinamento Interativo de Power BI")
st.write("A cada etapa, marque os itens concluídos, avalie a dificuldade e deixe observações!")

# Função para avaliação de dificuldade
def avaliacao_dificuldade(passo):
    st.subheader(f"Avaliação do {passo}")
    dificuldade = st.radio("Como você classificaria a dificuldade?", ["Fácil", "Médio", "Difícil"], key=f"{passo}_dificuldade")
    observacoes = st.text_area("Observações ou dificuldades encontradas:", key=f"{passo}_obs")
    return dificuldade, observacoes

# Primeiro Passo
st.header("Primeiro Passo: Compreender os Dados")
with st.form("passo1"):
    st.subheader("Importando e tratando dados de clientes")
    check1 = st.checkbox("Importar base de clientes")
    check2 = st.checkbox("Transformar dados com Power Query")
    check3 = st.checkbox("Renomear 'Planilha 1' para 'CadastroClientes'")
    check4 = st.checkbox("Apagar colunas 9 e 10 e testar Ctrl+Z")
    check5 = st.checkbox("Remover linhas em branco")
    check6 = st.checkbox("Usar a primeira linha como cabeçalho")
    check7 = st.checkbox("Transformar coluna CPF em texto")
    check8 = st.checkbox("Excluir coluna Número de Filhos")
    submitted1 = st.form_submit_button("Salvar progresso do Primeiro Passo")
    if submitted1:
        st.success("Progresso do Primeiro Passo salvo!")

dificuldade1, observacoes1 = avaliacao_dificuldade("Primeiro Passo")

# Segundo Passo
st.header("Segundo Passo: Relacionar Mais de Uma Tabela")
with st.form("passo2"):
    st.subheader("Relacionamentos entre tabelas")
    check9 = st.checkbox("Identificar tabelas fato e dimensões")
    check10 = st.checkbox("Criar relacionamento: Base Vendas + Cadastro Produtos")
    check11 = st.checkbox("Criar relacionamento: Base Vendas + Cadastro Clientes")
    check12 = st.checkbox("Criar relacionamento: Base Vendas + Calendário")
    check13 = st.checkbox("Criar relacionamento: Base Vendas + Cadastro Lojas")
    submitted2 = st.form_submit_button("Salvar progresso do Segundo Passo")
    if submitted2:
        st.success("Progresso do Segundo Passo salvo!")

dificuldade2, observacoes2 = avaliacao_dificuldade("Segundo Passo")

# Terceiro Passo
st.header("Terceiro Passo: Realizar Cálculos Adequados")
with st.form("passo3"):
    st.subheader("Colunas Calculadas e Medidas no DAX")
    check14 = st.checkbox("Criar coluna calculada: Tipo do Pedido")
    check15 = st.checkbox("Criar medida: Total de Pedidos")
    check16 = st.checkbox("Criar coluna Idade do Cliente")
    check17 = st.checkbox("Criar fórmulas de data (Ano, Mês, Dia da semana)")
    check18 = st.checkbox("Criar fórmulas de texto (Concatenar nome, abreviar mês)")
    check19 = st.checkbox("Criar fórmula de relacionamento (RELATED)")
    check20 = st.checkbox("Criar medidas de vendas de celular, maior/menor faturamento")
    submitted3 = st.form_submit_button("Salvar progresso do Terceiro Passo")
    if submitted3:
        st.success("Progresso do Terceiro Passo salvo!")

dificuldade3, observacoes3 = avaliacao_dificuldade("Terceiro Passo")

# Resultado Final
st.header("Resumo do Seu Progresso")
if st.button("Enviar progresso final"):
    st.success("Progresso enviado com sucesso! Obrigado por participar!")
    st.write("**Avaliação de Dificuldade:**")
    st.write(f"Primeiro Passo: {dificuldade1}")
    st.write(f"Segundo Passo: {dificuldade2}")
    st.write(f"Terceiro Passo: {dificuldade3}")
    st.write("**Observações:**")
    st.write(f"Primeiro Passo: {observacoes1}")
    st.write(f"Segundo Passo: {observacoes2}")
    st.write(f"Terceiro Passo: {observacoes3}")
    st.info("Essas informações podem ser exportadas para um arquivo ou enviadas a um servidor para acompanhamento.")
